# Hand-eye matrix units: mm.
# Default mode is camera_to_flange, so the matrix below is T_flange_camera.
# If your calibration outputs T_camera_flange, set mode: flange_to_camera.
mode: camera_to_flange

m00: -0.98
m01:  0.00
m02: -0.21
m03: -114.12

m10: -0.03
m11: -0.99
m12:  0.10
m13:  -44.02

m20: -0.21
m21:  0.10
m22:  0.97
m23:  125.38

m30: 0.00
m31: 0.00
m32: 0.00
m33: 1.00
